schema_version: 1

context:
  name: azure-mgmt-privatedns
  version: 1.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/azure-mgmt-privatedns-${{ version }}.zip
  sha256: b60f16e43f7b291582c5f57bae1b083096d8303e9d9958e2c29227a55cc27c45

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}
    - azure-common >=1.1,<2.0
    - azure-mgmt-core >=1.2.0,<2.0
    - msrest >=0.5.0

tests:
  - python:
      imports:
        - azure.mgmt.privatedns
        - azure.mgmt.privatedns.aio
      pip_check: true
      python_version: ${{ python_min }}.*
about:
  summary: Microsoft Azure DNS Private Zones Client Library for Python
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
